logging: Fix Logging level
kata-containers/runtime pull request #3040
Opened 2020-11-01 16:06 UTC by marcel-apf

When running CRI-O in normal mode and setting enable_debug = true
in configuration.toml, the logging level should be info
(which from KATA's perspective behaves like DEBUG).
However the runtime logging level will be  WARN (which from KATA's
perspective behaves like INFO).

The issue can be traced to commit
    eee4d70 "katutils: logging: default log level to Warn".

Fix it by setting the logging level whether the debugging mode is
enabled or not.

Fixes: #3039

Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>

2020-11-01 20:17 UTC, fidencio commented
/test

2020-11-01 20:25 UTC, fidencio commented
@marcel-apf, thanks for the patch. We've discussed this offline and I'd like to know the opinion of the other developers as this patch is the first piece of something that will be a bigger work.

Long-story-short, we should start dealing with our logs in a more standardized way, then we'll allow the admin setting the log_level via the configuration.toml file. This would allow us to have fine grain what we want to see and will help with debuggability.

Anyways, I couldn't wrap my mind around whether this is a valid effort for 1.x or whether it'd be too intrusive at this point. And here we're, getting back to http://lists.katacontainers.io/pipermail/kata-dev/2020-October/001561.html, which would be really good to have more opinions there.

2020-11-03 14:18 UTC, devimc commented
thanks @marcel-apf 

> When running CRI-O in normal mode and setting enable_debug = true in configuration.toml, the logging level should be info

what's the expected logging level in containerd?

2020-11-03 14:28 UTC, fidencio commented
> thanks @marcel-apf
> 
> > When running CRI-O in normal mode and setting enable_debug = true in configuration.toml, the logging level should be info
> 
> what's the expected logging level in containerd?

https://github.com/containerd/containerd/blob/master/docs/ops.md says that containerd has the following log levels: "debug, info, warn, error, fatal, panic", meaning it does match with CRI-O. Their manpage mentions that "info" in the default log level (when in debug mode).

Does this answer your question, @devimc?

2020-11-08 08:06 UTC, marcel-apf commented
@fidencio thank you for you help! Please let me know if there is anything I have missed or I should further do.

2020-11-08 16:57 UTC, marcel-apf commented
/retest

2020-11-09 09:42 UTC, jodh-intel requested changes
Hi @marcel-apf - thanks for raising, but I'm afraid this isn't clear to me.

If I'm understanding correctly, this change is intended to be cri-o specific, but the change will affect all container managers surely?

The change also looks confusing and fwics means you can not enable true debug output?

2020-11-09 10:15 UTC, marcel-apf commented
Hi @jodh-intel, 
> Hi @marcel-apf - thanks for raising, but I'm afraid this isn't clear to me.
> 
> If I'm understanding correctly, this change is intended to be cri-o specific, but the change will affect all container managers surely?

Not really, this change is intended to give "priority" to the log-level settings in the runtime configuration (if set to "debug"). 
Also is more about the runtime behavior when it does not receive the "debug" flag. However, the error is easily reproducible when using cri-o, and since I proposed the PR as a fix, I thought is best If I "connect" the fix to the way I found it.

> 
> The change also looks confusing and fwics means you can not enable true debug output?

I have to agree with you about the confusing part, but I think it may be related to the way the logging is initialized. 
To answer your question, you cannot enable true debug output if the "-debug" flag is not passed as parameter to the runtime, that is at least how I understand the situation .

Zooming in, the code only addresses the configuration debug field only if is set to "false", assuming that otherwise the default configuration will set the logging to debug mode. However, that is not true after commit  eee4d70.

2021-05-04 18:19 UTC, fidencio commented
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

2021-05-04 18:19 UTC, closed without merging