cli: Fix the incorrect info of command "kata-runtime exec"
kata-containers/runtime pull request #3153
Opened 2021-04-02 03:49 UTC by LiangZhou-CTY

When user runs "kata-runtime exec test something" and then the help information prompted,
the "EXAMPLE" field of the help information missed "exec", see:

# kata-runtime <container-id> ps

Obviously it missed the word "exec" following the "kata-runtime".

2021-04-06 13:05 UTC, snir911 approved these changes
LGTM thanks!

2021-04-06 13:05 UTC, snir911 commented
/test

2021-04-07 05:55 UTC, liubin approved these changes

2021-04-07 05:58 UTC, liubin commented
@LiangZhou-CTY thank you for this PR, but there are some checks that failed, you can correct your commit message by reading [this](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#github-best-practices).

2021-04-07 07:23 UTC, LiangZhou-CTY commented
> @LiangZhou-CTY thank you for this PR, but there are some checks that failed, you can correct your commit message by reading [this](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#github-best-practices).

Thank you @liubin , I checked the link you provided and I'm still not clear how to make the PR go further.
Currently  there're three checks failure:

> DCO check / DCO Check (pull_request) 
Run tim-actions/get-pr-commits@ed97a21c3f83c3417e67a4733ea76887293a2c8f
  with:
	token: ***
Error: Not Found

I have no idea what does this mean, would you please help me check it?

> Ensure PR has required porting labels / check-pr-porting-labels (pull_request_target) 

Seems that I cannot add "label" in this PR. And more, if I can add label, which label I should use to add to this PR please ?

> Move issues to "In progress" in backlog project when referenced by a PR / move-linked-issues-to-in-progress (pull_request_target) 
Seems that I cannot change the status of the issue.

Thank you in advance for your time.

2021-04-07 07:54 UTC, liubin commented
Hi @LiangZhou-CTY , for this PR, you only need to fix your commit message, then re-push to your branch, the DCO and  “Move issues to ...” will be corrected automaticly.

You can refer to other commits from [merged PRs](https://github.com/kata-containers/runtime/pulls?q=is%3Apr+is%3Amerged). 

For your commits:

```
cli: Fix the incorrect help information of the command "kata-runtime …

…exec"

When user runs "kata-runtime exec test something" and then the help information prompted,
the "EXAMPLE" field of the help information missed "exec", see:
# kata-runtime <container-id> ps

Obviously it missed the word "exec" following the "kata-runtime".
```

There 3 problems:

- title line is too long and be split, you should make it shorter.
- no `Fixes: #xxx`, you need to add this to your commit message body.
- no `Signed-off-by`. This can be done by `git commit -s` or `git commit -s --amend`. This will fix the DCO check failure.

I noticed you have the correct commit message if this PR's body, but not the git commit message itself.

You can feel free to try to update your commit, push it to GitHub and then check the CI's checks result.

2021-04-07 11:35 UTC, LiangZhou-CTY commented
Thank you @liubin for your help, now the DCO  is pass.

2021-04-07 12:10 UTC, snir911 commented
/test

2021-04-07 13:21 UTC, liubin requested changes
@LiangZhou-CTY  Your commit message contains:

```
Signed-off-by: LiangZhou-CTY <81076799+LiangZhou-CTY@users.noreply.github.com>
```

2021-04-07 14:25 UTC, LiangZhou-CTY commented
> @LiangZhou-CTY Your commit message contains:
> 
> ```
> Signed-off-by: LiangZhou-CTY <81076799+LiangZhou-CTY@users.noreply.github.com>
> ```

When I firstly use the string "Signed-off-by Liang Zhou <zhoul110@chinatele.com>" , the DCO failed and said that it's expecting "LiangZhou-CTY <81076799+LiangZhou-CTY@users.noreply.github.com>", so I had to change to the string you mentioned in commit message to make DCO pass.  Anything I missed ?

2021-04-07 15:10 UTC, liubin commented
@LiangZhou-CTY have you [set your email at GitHub](https://docs.github.com/cn/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address) and configured it for git?

2021-04-08 01:53 UTC, LiangZhou-CTY commented
@liubin Thank you Bin for your patient guide to my first PR in github and sorry for my clumsy operations. I changed the author info, please have a check again.

2021-04-08 02:19 UTC, liubin approved these changes

2021-04-08 02:20 UTC, liubin commented
/test

2021-04-08 02:36 UTC, liubin commented
hi, @LiangZhou-CTY PRs are always welcome.
I tried to send you an email from Gmail but refused by your mail server's spam policy, so can you and my WeChat **sakura79** for further communication?

2021-04-08 02:55 UTC, LiangZhou-CTY commented
> hi, @LiangZhou-CTY PRs are always welcome.
> I tried to send you an email from Gmail but refused by your mail server's spam policy, so can you and my WeChat **sakura79** for further communication?

Yes, sure. 
I didn't find "sakura79"  from the wechat, please reach me by my gmail  lullaby2005 at gmail dot com  . 

Thanks.

2021-04-08 03:27 UTC, Tim-Zhang approved these changes

2021-04-08 08:09 UTC, LiangZhou-CTY commented
Seems that the four failures are not caused by my modification but the testbed related , is there any idea about how to move this PR go ahead please?

2021-04-08 08:16 UTC, liubin commented
@LiangZhou-CTY don't worry, these failed tests may sometimes fail, and will not block your PR to be merged.

2021-04-08 08:22 UTC, lifupan approved these changes

2021-04-08 08:22 UTC, merged